## Linear Regression
- It is a method to help us to understand the relationship between two variables: The predictor(independent) variable x sometime called feature, the target variable(dependent) y
- IN pytorch, we call prediction step the forward step

In [1]:
import torch

In [2]:
#Define w=2 and b=-1 for y=wx+b
w=torch.tensor(2.0,requires_grad=True)
b=torch.tensor(-1.0,requires_grad=True)

In [3]:
#Then define the function forward(x,w,b)makes the prediction
def forward(x):
    yhat=w*x+b
    return yhat

In [4]:
#predict y=2x-1 at x=1
x=torch.tensor([[1.0]])
yhat=forward(x)
print('The prediction: ',yhat)

The prediction:  tensor([[1.]], grad_fn=<AddBackward0>)


In [5]:
# Create x Tensor and check the shape of x tensor

x = torch.tensor([[1.0], [2.0]])
print("The shape of x: ", x.shape)

The shape of x:  torch.Size([2, 1])


In [6]:
# Make the prediction of y = 2x - 1 at x = [1, 2]

yhat = forward(x)
print("The prediction: ", yhat)

The prediction:  tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)


## Class Linear
- The Linear class can be used to make a prediction.

In [7]:
from torch.nn import Linear

In [8]:
torch.manual_seed(1)

In [9]:
#Create Linear Regression model, and print out the parameter
#in feature is the size of each input sample or the number of columns
#out feature  is the size of each output sample
lr=Linear(in_features=1,out_features=1,bias=True)
print('Parameter w and b: ',list(lr.parameters()))

Parameter w and b:  [Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


A method  <code>state_dict()</code> Returns a Python dictionary object corresponding to the layers of each parameter  tensor. 


In [10]:
print("Python dictionary: ",lr.state_dict())
print("keys: ",lr.state_dict().keys())
print("values: ",lr.state_dict().values())

Python dictionary:  OrderedDict([('weight', tensor([[0.5153]])), ('bias', tensor([-0.4414]))])
keys:  odict_keys(['weight', 'bias'])
values:  odict_values([tensor([[0.5153]]), tensor([-0.4414])])


In [11]:
print('weight',lr.weight)
print('bias',lr.bias)

weight Parameter containing:
tensor([[0.5153]], requires_grad=True)
bias Parameter containing:
tensor([-0.4414], requires_grad=True)


In [12]:
#Make the prediction at x=[[1.0]]
x=torch.tensor([[1.0]])
yhat=lr(x)
print('The prediction:',yhat)

The prediction: tensor([[0.0739]], grad_fn=<AddmmBackward0>)


In [13]:
x=torch.tensor([[1.0],[2.0]])
yhat=lr(x)
print('The prediction: ',yhat)

The prediction:  tensor([[0.0739],
        [0.5891]], grad_fn=<AddmmBackward0>)


## Build Custom Modules

In [14]:
from torch import nn


In [15]:
# Customize Linear Regression Class

class LR(nn.Module):
    
    # Constructor
    def __init__(self, input_size, output_size):
        
        # Inherit from parent
        super(LR, self).__init__()
        self.linear = nn.Linear(input_size, output_size)
    
    # Prediction function
    def forward(self, x):
        out = self.linear(x)
        return out

In [16]:
# Create the linear regression model. Print out the parameters.

lr = LR(1, 1)
print("The parameters: ", list(lr.parameters()))
print("Linear model: ", lr.linear)

The parameters:  [Parameter containing:
tensor([[-0.1939]], requires_grad=True), Parameter containing:
tensor([0.4694], requires_grad=True)]
Linear model:  Linear(in_features=1, out_features=1, bias=True)


In [17]:
# Try our customize linear regression model with single input

x = torch.tensor([[1.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[0.2755]], grad_fn=<AddmmBackward0>)
